# Generated by Django 5.2.6 on 2025-09-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('menswear', 'Menswear'), ('womenswear', 'Womenswear'), ('kidswear', 'Kidswear'), ('exclusive', 'Exclusive'), ('accessories', 'Accessories')], default='update', max_length=20),
        ),
    ]
